### ISSUE TITLE
TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by cgarcia369** [kimjbstar/sequelize-typescript-migration#9]
Hi , i got this error and i don't have idea what to do , anyone can help me ?

```
import { Sequelize } from 'sequelize-typescript'
// import { Person } from '../models/test.model';
const path = require('path')

export const sequelize : Sequelize = new Sequelize({
  database: 'test',
  dialect: 'mysql',
  username: 'root',
  password: '',
  storage: ':memory:',
  models: [] // or [Player, Team],
})

```
```
listen():boolean {
    return this.app.listen(process.env.PORT || 8080, async (err: any, callback: any):Promise<Boolean> => {
      console.log('Servidor conectado en puerto', process.env.PORT)
      await sequelize.addModels([Person])
      // let f: Date = new Date();
      // let birtDate = f.getDate() + "-"+ f.getMonth()+ "-" +f.getFullYear();
      // Person.create({name:'Camilo',date: birtDate})
      if(err){
        return false
      }
      return true;
    })
  }
```

```
sequelize(): void{
    (async () => {
      try {
        await SequelizeTypescriptMigration.makeMigration(sequelize, {
          outDir: path.join(__dirname, "../migrations"),
          migrationName: "qrleanMigration",
          preview: false,
        });
      }catch (e) {
        console.log(e)
      }
    })();
  }
```

this error appeared from nowhere.

TypeError: Cannot read property 'length' of undefined
    at C:\Users\F\Desktop\QrleanProyecto\Backend\node_modules\sequelize-typescript-migration\dist\utils\getDiffActionsFromTables.js:15:33
    at Array.forEach (<anonymous>)
    at Object.getDiffActionsFromTables [as default] (C:\Users\F\Desktop\QrleanProyecto\Backend\node_modules\sequelize-typescript-migration\dist\utils\getDiffActionsFromTables.js:11:16)
    at Function.SequelizeTypescriptMigration.makeMigration (C:\Users\F\Desktop\QrleanProyecto\Backend\node_modules\sequelize-typescript-migration\dist\index.js:35:57)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

**Comment by cgarcia369** [comment]
solution: Delete all tables from database

**Comment by mricharz** [comment]
> solution: Delete all tables from database

yeah, ... this is exactly how migrations should work.... -,-
i have the same error and no solution.

i can remove the whole db recreate it using migrations. :heavy_check_mark:
if i run detection again after editing some models... :x: and this is the purpose of this NPM-Package isn't it?

any ideas?

**Comment by mricharz** [comment]
Fixed it with the PR above.
